version: '3.4'

services:
  mssql-server:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: p4ssw0rD
    ports:
      - 2433:1433
    volumes:
      - "mssql-server:/var/opt/mssql"
  adminer:
    image: adminer:4.8.1
    ports:
      - 2431:8080
    environment:
      TZ: Europe/Rome
      ADMINER_DEFAULT_SERVER: mssql-server

  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:3.9.0'    
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka
    image: 'bitnami/kafka:3.1.0'    
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=host.docker.internal:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper            
    
  gestionestanze:
    build:
      context: ../microservizi/GestioneStanze/
      dockerfile: GestioneStanze.Api/Dockerfile  
    image: ghcr.io/moonlight735/gestionestanze:latest
    pull_policy: always
    depends_on:
      - mssql-server
    environment:
      TZ: Europe/Rome
    volumes:
      - "./config/gestionestanze-appsettings.json:/app/appsettings.json:ro"

  gestioneutente:
    build:
      context: ../microservizi/GestioneUtente/
      dockerfile: GestioneUtente.API/Dockerfile   
    image: ghcr.io/moonlight735/gestioneutente:latest
    pull_policy: always
    depends_on:
      - mssql-server
    environment:
      TZ: Europe/Rome
    volumes:
      - "./config/gestioneutente-appsettings.json:/app/appsettings.json:ro"
    
  gestionegioco:
    build:
      context: ../microservizi/GestioneGioco/
      dockerfile: GestioneGioco.API/Dockerfile   
    image: ghcr.io/moonlight735/gestionegioco:latest
    pull_policy: always
    depends_on:
      - mssql-server
    environment:
      TZ: Europe/Rome
    volumes:
      - "./config/gestionegioco-appsettings.json:/app/appsettings.json:ro"

  gestionetorneo:
    build:
      context: ../microservizi/GestioneTorneo/
      dockerfile: GestioneTorneo.API/Dockerfile   
    image: ghcr.io/moonlight735/gestionetorneo:latest
    pull_policy: always
    depends_on:
      - mssql-server
      - kafka
    environment:
      TZ: Europe/Rome
      MOONLIGHT735_NUGET_USERNAME: ${MOONLIGHT735_NUGET_USERNAME}
      MOONLIGHT735_NUGET_PASSWORD: ${MOONLIGHT735_NUGET_PASSWORD}      
    volumes:
      - "./config/gestionetorneo-appsettings.json:/app/appsettings.json:ro"
      
volumes:
  mssql-server:
  
 